routes/web.php
<?php

Route::prefix('admin')->group(function (){

    Route::get('/','LoginController@login')->name('login');
//    ->middleware('LoginValidate')
    Route::post('validatedData','LoginController@validatedData')->name('validatedData');
    Route::post('logout/{user}','LoginController@logout')->name('logout');

    Route::resource('dashboard','DashboardController');
//    ->middleware('ValidateUser')
    Route::prefix('students')->group(function (){
        Route::resource('data', 'StuDataController',['except'=>['create','store']]);
        Route::resource('black_list','BlackListController');
        Route::any('drop_out','StudentController@drop_out')->name('students_drop_out');
        Route::any('drop_in','StudentController@drop_in')->name('students_drop_in');
        Route::any('drop_all','StudentController@drop_all')->name('students_drop_all');
        Route::any('drop_mail_config','StudentController@drop_mail_config')->name('students_drop_mail_config');
    });

    Route::prefix('Class')->group(function (){
        Route::resource('course','CourseController');
        Route::resource('course_level','CourseLevelController',['only'=>['index','create','destroy']]);
        Route::resource('course_data','CourseDataController');
        Route::resource('subject_class','SubjectClassController');
        Route::resource('sup_elective','SupElectiveController');
    });

    Route::prefix('Grade')->group(function (){
        Route::resource('work_grade','WorkGradeController');
        Route::resource('UnReport','UnreportController',['only'=>['index']]);
        Route::post('UnReport_mail','UnreportController@mail_notice')->name('UnReport_mail');
        Route::post('UnReport_all_mail','UnreportController@all_mail_notice')->name('UnReport_all_mail');
        Route::resource('students_grade','StudentGradeController');
        Route::get('de_sing','GradeController@de_sing')->name('de_sing');
        Route::get('de_sing_list_grade','GradeController@de_sing_list_grade')->name('de_sing_list_grade');
    });

    Route::prefix('Update')->group(function (){
        Route::resource('students_update','StudentsUpdateController');
        Route::post('all_update','StudentsUpdateController@all_update')->name('update');
        Route::post('exception_update/{id}','StudentsUpdateController@exception_update')->name('exception_update');
        Route::post('keyin_exception_update','StudentsUpdateController@keyin_exception_update')->name('keyin_exception_update');
        Route::resource('recode_update','UpdateRecodeController');
    });

//    Route::prefix('Forum')->group(function (){
//        Route::prefix('theme')->group(function (){
//            Route::any('theme','ForumController@theme')->name('forum_theme');
//            Route::post('/add','ForumController@theme_add')->name('forum_theme_add');
//            Route::post('/edit/{id}','ForumController@theme_edit')->name('forum_theme_edit');
//            Route::post('/delete/{id}','ForumController@theme_delete')->name('forum_theme_delete');
//        });
//    });

    Route::prefix('announcement')->group(function (){
        Route::resource('bulletin','BulletinController');
        Route::post('create_type','BulletinController@create_type')->name('create_type');
        Route::delete('delete_relies/{replies}','BulletinController@delete_relies')->name('delete_relies');
    });

    Route::prefix('email_config')->group(function (){
        Route::prefix('drop')->group(function (){
            Route::any('/','EmailController@drop_show')->name('email_config_drop');
            Route::post('out/{type}','EmailController@email_config')->name('email_config_dropout');
            Route::post('in/{type}','EmailController@email_config')->name('email_config_dropin');
        });
        Route::prefix('update')->group(function (){
            Route::any('/','EmailController@update_show')->name('email_config_update');
            Route::post('save/{type}','EmailController@email_config')->name('email_config_update_save');
        });
        Route::prefix('enrollment')->group(function (){
           Route::any('/','EmailController@enrollment_show')->name('email_config_enrollment');
           Route::post('save/{type}','EmailController@email_config')->name('email_config_enrollment_save');
        });
    });

    Route::prefix('Edit')->group(function (){
        //入學指導
        Route::prefix('guidance')->group(function (){
            Route::any('/','EditController@admission_guidance')->name('edit_admission_guidance');
            Route::post('save/{type}','EditController@edit')->name('edit_admission_guidance_save');
        });
        //教學計畫
        Route::prefix('plan')->group(function (){
            Route::any('/','EditController@plan')->name('edit_plan');
            Route::post('save/{type}','EditController@edit')->name('edit_plan_save');
        });
        //認識學院
        Route::prefix('understanding')->group(function (){
            Route::any('/','EditController@understanding')->name('edit_understanding');
            Route::post('save/{type}','EditController@edit')->name('edit_understanding_save');
        });
        //年度行事曆
        Route::prefix('calendar')->group(function (){
            Route::any('/','EditCalendarController@calendar')->name('edit_calendar');
            Route::post('/save/{year}/{month}','EditCalendarController@calendar_save')->name('calendar_save');
        });
        //說明看板
        Route::prefix('description')->group(function (){
            Route::any('/','EditController@description')->name('edit_description');
            Route::post('save/{type}','EditController@edit')->name('edit_description_save');
        });
        //訊息公告
        Route::prefix('announcement')->group(function (){
            Route::any('/','EditController@announcement')->name('edit_announcement');
            Route::post('/mange/{config}','EditController@announcement_mange')->name('edit_announcement_mange');
            Route::post('/save/{type}','EditController@edit')->name('edit_announcement_save');
        });
    });

    Route::prefix('File')->group(function (){
        Route::resource('scripture','FileScriptureController');
        Route::resource('teaching_material','FileTeachingMaterial');
    });

    Route::prefix('administration')->group(function (){
        Route::resource('role','RoleController');
        Route::resource('account','AccountController');
    });
});

Route::any('test','TestController@test');
//Route::any('testshow','TestController@testshow');

resources/views/de_sing.blade.php
@extends('layouts.layout')

@push('script')
    <script>
        $(document).ready(function () {
            $('li[name=grade_li]').addClass('active');
            $('div[name=grade]').addClass('show');
        });
    </script>
@endpush
@section('navbar')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">成績管理</li>
        <li class="breadcrumb-item text_label">德行成績</li>
    </ol>
@endsection
@section('content')
    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-8">
                    <form class="form-inline" action="{{ route('grade_work') }}" id="term">
                        <div class="input-group">
                            <label for="sel1">班級:</label>
                            <select class="form-control" id="sel1">
                                <option>基礎班一</option>
                                <option>基礎班二</option>
                                <option>本科班一</option>
                                <option>本科班二</option>
                                <option>本科班三</option>
                                <option>專科班一</option>
                                <option>專科班二</option>
                                <option>專科班三</option>
                                <option>專科班四</option>
                            </select>
                        </div>
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="查詢學號.....">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit"><i class="fas fa-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-4">
                </div>
                <div class="col-12" style="padding-top: 1%;text-align: center">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>班級</th>
                            <th>學號</th>
                            <th>姓名</th>
                            <th>德行平均成績</th>
                            <th>詳細成績表</th>
                        </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>基礎班一</td>
                                <td>eb123456</td>
                                <td>Doe</td>
                                <td>A</td>
                                <td><a href="{{ route('de_sing_list_grade') }}" class="btn btn-lg" style="color: #1d68a7"><i class="fas fa-clipboard-list"></i></a></td>
                            </tr>
                            <tr>
                                <td>基礎班一</td>
                                <td>eb123456</td>
                                <td>Moe</td>
                                <td>A</td>
                                <td><a href="{{ route('de_sing_list_grade') }}" class="btn btn-lg" style="color: #1d68a7"><i class="fas fa-clipboard-list"></i></a></td>
                            </tr>
                            <tr>
                                <td>基礎班一</td>
                                <td>rb123456</td>
                                <td>Dooley</td>
                                <td>A</td>
                                <td><a href="{{ route('de_sing_list_grade') }}" class="btn btn-lg" style="color: #1d68a7"><i class="fas fa-clipboard-list"></i></a></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- /.container-fluid-->
        <!-- /.content-wrapper-->
    </div>
@endsection

resources/views/de_sing_list_grade.blade.php
@extends('layouts.layout')

@push('script')
    <script>
        $(document).ready(function () {
            $('li[name=grade_li]').addClass('active');
            $('div[name=grade]').addClass('show');

        });
    </script>
@endpush
@section('navbar')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">成績管理</li>
        <li class="breadcrumb-item">德行成績</li>
        <li class="breadcrumb-item text_label">個人德行詳細成績</li>
    </ol>
@endsection
@section('content')
    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-8">
                    <a href="{{ route('de_sing') }}" class="btn btn-primary"><i class="fas fa-arrow-left"></i>返回</a>
                </div>
                <div class="col-4">
                </div>
                <div class="col-12" style="padding-top: 1%;text-align: center">
                    <div class="d-flex" style="padding-bottom: 1%">
                        <div class="p-2 bg-warning flex-fill">班級：</div>
                        <div class="p-2 bg-warning flex-fill">學號：</div>
                        <div class="p-2 bg-warning flex-fill">姓名：</div>
                    </div>
                    <table class="table">
                        <thead>
                        <tr>
                            <th>項目</th>
                            <th>最新一天成績</th>
                            <th>一個月平均成績</th>
                            <th>總平均成績</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>弟子規</td>
                            <td>100</td>
                            <td>100</td>
                            <td>100</td>
                        </tr>
                        <tr>
                            <td>感應篇</td>
                            <td>100</td>
                            <td>100</td>
                            <td>100</td>
                        </tr>
                        <tr>
                            <td>十善業</td>
                            <td>100</td>
                            <td>100</td>
                            <td>100</td>
                        </tr>
                        <tr>
                            <td>功過格</td>
                            <td>100</td>
                            <td>100</td>
                            <td>100</td>
                        </tr>
                        <tr>
                            <td>自我評量</td>
                            <td>100</td>
                            <td>100</td>
                            <td>100</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- /.container-fluid-->
        <!-- /.content-wrapper-->
    </div>
@endsection

resources/views/edit_requirements.blade.php
@extends('layouts.layout')

@push('script')
    <script>
        $(document).ready(function () {
            $('li[name=edit_li]').addClass('active');
            $('div[name=edit]').addClass('show');

            $('textarea').summernote({
                tabsize: 3,
                height: 600
            });
        });
    </script>
@endpush
@section('navbar')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">頁面編輯</li>
        <li class="breadcrumb-item text_label"><b>休學通知</b></li>
    </ol>
@endsection
@section('content')
    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-8">
                    <h2>課程介紹</h2>
                </div>
                <div class="col-4">
                    <a href="#" class="btn btn-primary" style="float: right"><i class="fas fa-save"></i> 保存</a>
                </div>
                <div class="col-12" style="padding-top: 1rem">
                    <ul class="nav nav-pills nav-justified">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#home">基礎學科</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#menu1">本科學科</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#menu2">專科學科</a>
                        </li>
                    </ul>

                    <div class="tab-content" style="padding-top: 1%">
                        <div class="tab-pane container active" id="home">
                            <textarea id="message_edit" name="basis"></textarea>
                        </div>
                        <div class="tab-pane container fade" id="menu1">
                            <textarea id="message_edit" name="bachelor"></textarea>
                        </div>
                        <div class="tab-pane container fade" id="menu2">
                            <textarea id="message_edit" name="specialist"></textarea>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- /.container-fluid-->
        <!-- /.content-wrapper-->
    </div>
@endsection

resources/views/forum_theme.blade.php
@extends('layouts.layout')

@push('script')
    <script>
        $(document).ready(function () {
            $('li[name=discussion_li]').addClass('active');
            $('div[name=discussion]').addClass('show');
        });
    </script>
@endpush
@section('navbar')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">討論版管理</li>
        <li class="breadcrumb-item text_label"><b>主題編輯</b></li>
    </ol>
@endsection
@section('content')
    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-8">
                    <h2>討論版主題</h2>
                </div>
                <div class="col-4">
                    <button class="btn btn-primary" style="float: right" data-toggle="modal" data-target="#new">新增主題</button>
                </div>
                <div class="col-12 pt-3">
                    <div class="row">
                        @foreach($data as $v)
                        <div class="col-12 col-sm-6 col-md-6 col-lg-4 pb-3">
                            <div class="card bg-primary text-white">
                                <div class="card-body row">
                                    <div class="col-8">
                                        {{ $v->name }}
                                    </div>
                                    <div class="col-4" style="text-align: right">
                                        <a href="#edit{{ $v->id }}" style="color: white;font-size: 1.2rem" data-toggle="modal"><i class="fas fa-edit"></i></a>
                                        <a href="#delete{{ $v->id }}" style="color: red;font-size: 1.2rem" data-toggle="modal"><i class="fas fa-times"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @endforeach
                    </div>

                </div>
            </div>
        </div>
        <!-- /.container-fluid-->
        <!-- /.content-wrapper-->
    </div>
@endsection
@include('modals.forum_theme_edit')
@include('modals.forum_theme_new')
@include('modals.forum_theme_delete')

resources/views/index.blade.php
@extends('admin.layouts.layout')
@push('script')
    <script>
        $(document).ready(function () {
            $('li[name=dashboard_li]').addClass('active');
        });
    </script>
@endpush
@section('content')
    <div class="row align-items-stretch">

        <div class="col-lg-12 mb-12">
            <!-- Dropdown Card Example -->
            <div class="card border-0 shadow mb-4">
                <div class="card-header border-0 py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">依學年度統計學生聽課次數{{ $user->name }}</h6>
                    <!-- Card Header Dropdown -->
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownCardExample" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw ml-1 text-gray-400"></i>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right border-0 shadow animated--fade-in" aria-labelledby="dropdownCardExample">
                            <div class="dropdown-header">Dropdown Header:</div>
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    Dropdown menus can be placed in the card header in order to extend the functionality of a basic card. In this dropdown card example, the Font Awesome vertical ellipsis icon in the card header can be clicked on in order to toggle a dropdown menu.
                </div>
            </div>

            <!-- Dropdown Card Example -->
            <div class="card border-0 shadow mb-4">
                <div class="card-header border-0 py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">依學生個人統計聽課次數</h6>
                    <!-- Card Header Dropdown -->
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownCardExample" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw ml-1 text-gray-400"></i>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right border-0 shadow animated--fade-in" aria-labelledby="dropdownCardExample">
                            <div class="dropdown-header">Dropdown Header:</div>
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    Dropdown menus can be placed in the card header in order to extend the functionality of a basic card. In this dropdown card example, the Font Awesome vertical ellipsis icon in the card header can be clicked on in order to toggle a dropdown menu.
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/student_drop_all.blade.php
@extends('layouts.layout')
@push('script')
<script>
    $(document).ready(function() {
        $('li[name=student_li]').addClass('active');
        $('div[name=student]').addClass('show');
    });
</script>
@endpush
@section('navbar')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">學生管理</li>
        <li class="breadcrumb-item">修復學管理</li>
        <li class="breadcrumb-item text_label">歷史紀錄</li>
    </ol>
@endsection
@section('content')
    <div class="row align-items-stretch">
        <div class="col-12">
            <div class="row">
                <div class="col-4">
                </div>
                <div class="col-8">
                    <form class="form-inline" action="" style="float: right">
                        <label for="search" class="mr-sm-2">搜尋：</label>
                        <input type="text" class="form-control mb-2 mr-sm-2" id="search" placeholder="姓名\學號\電子郵件\電話"
                               size="30">
                        <button type="submit" class="btn btn-primary mb-2"><i class="fa fa-search"></i></button>
                    </form>
                </div>

                <div class="col-12">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>管理</th>
                            <th>核准</th>
                            <th>學號</th>
                            <th>年限</th>
                            <th>休學原因</th>
                            <th>申請日期</th>
                            <th>休學日期</th>
                            <th>復學日期</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                <a href="#" style="color: red;font-size: 1.3rem"><i class="fa fa-trash"></i></a>&nbsp;&nbsp;&nbsp;
                            </td>
                            <td>待核定</td>
                            <td>eb42282</td>
                            <td>1</td>
                            <td>測試</td>
                            <td>2018/9/26</td>
                            <td>2018/9/26</td>
                            <td></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/sup_elective_course.blade.php
@extends('admin.layouts.layout')

@push('script')
    <script>
        $(document).ready(function () {
            $('li[name=course_li]').addClass('active');
            $('div[name=course]').addClass('show');
        });
    </script>
@endpush
@section('navbar')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">科目學分課程</li>
        <li class="breadcrumb-item text_label"><b>選課管理及輔助選課</b></li>
    </ol>
@endsection
@section('content')
    <div class="content-wrapper">
        <div class="alert {{ $config->config == 1 ? "alert-success":"alert-danger" }}">
            <strong>開放選課狀態!</strong> [ {{ $config->config == 1 ? "開啟":"關閉" }} ]
        </div>

        <div class="container-fluid">
            <div class="row">
                <div class="col-8">
                    <form class="form-inline" action="{{ route('sup_elective.index') }}">
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" name="search" placeholder="查詢學號.....">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit"><i class="fas fa-search"></i></button>
                            </div>
                        </div>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    </form>
                </div>
                <div class="col-4">
                    <button class="btn btn-info" data-toggle="modal" data-target="#auto_elective_course" style="float: right">選課開放管理</button>
                </div>
                <div class="col-12">
                    <div class="d-flex" style="">
                        <div class="p-2 bg-warning flex-fill">班級：{{ $data->level->level ?? "" }}</div>
                        <div class="p-2 bg-warning flex-fill">學號：{{ $data->student_id ?? "" }}</div>
                        <div class="p-2 bg-warning flex-fill">姓名：{{ $data->name ?? "" }}</div>
                    </div>
                    <h3 style="text-align: center;padding-top: 1%">已選的課程</h3>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>管理</th>
                                <th>課程編號</th>
                                <th>標題</th>
                                <th>修別</th>
                                <th>授課老師</th>
                                <th>備註</th>
                            </tr>
                        </thead>
                        <tbody class="table-primary">
                        @if(!empty($data))
                            @foreach($data->curriculas as $v)
                                @if($v->course->level == $data->course_level)
                                    <tr>
                                        <td>
                                            <button class="btn" data-toggle="modal" data-target="#ck_remove{{ $v->id }}"><i class="fas fa-minus" style="color: red"></i></button>
                                        </td>
                                        <td>{{ $v->course->coursedata->sn }}</td>
                                        <td>{{ $v->course->coursedata->title }}</td>
                                        <td style="color: {{ $v->course->compulsory == 1 ? "red":"green"}}">{{ $v->course->compulsory == 1 ? "必修":"選修" }}</td>
                                        <td>{{ $v->course->coursedata->teacher }}</td>
                                        <td>{{ $v->course->remark }}</td>
                                    </tr>
                                @endif
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
                <div class="col-12">
                    <h3 style="text-align: center">可加選的選修課程</h3>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>加選</th>
                                <th>課程編號</th>
                                <th>標題</th>
                                <th>修別</th>
                                <th>授課老師</th>
                                <th>備註</th>
                            </tr>
                        </thead>
                        <tbody class="table-danger">
                        @if(!empty($data))
                            @foreach($data->level->curricula()->whereNotIn('id',$data->curriculas()->pluck('curricula'))->get() as $v)

                                <tr>
                                    <td>
                                        <button class="btn" data-toggle="modal" data-target="#ck_add{{ $v->id }}"><i class="fas fa-plus" style="color: green"></i></button>
                                    </td>
                                    <td>{{ $v->coursedata->sn }}</td>
                                    <td>{{ $v->coursedata->title }}</td>
                                    <td style="color: {{ $v->compulsory == 1 ? "red":"green"}}">{{ $v->compulsory == 1 ? "必修":"選修" }}</td>
                                    <td>{{ $v->coursedata->teacher }}</td>
                                    <td>{{ $v->remark }}</td>
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- /.container-fluid-->
        <!-- /.content-wrapper-->
    </div>
@endsection
@include('modals.sup_elective_course_management')
@include('modals.sup_elective_course_ck_add')
@include('modals.sup_elective_course_ck_remove')