routes/web.php
<?php

Route::prefix('admin')->group(function (){

    Route::get('/','LoginController@login')->name('login');
//    ->middleware('LoginValidate')
    Route::post('validatedData','LoginController@validatedData')->name('validatedData');
    Route::post('logout/{user}','LoginController@logout')->name('logout');

    Route::resource('dashboard','DashboardController');
//    ->middleware('ValidateUser')
    Route::prefix('students')->group(function (){
        Route::resource('data', 'StuDataController',['except'=>['create','store']]);
        Route::resource('black_list','BlackListController');
        Route::any('drop_out','StudentController@drop_out')->name('students_drop_out');
        Route::any('drop_in','StudentController@drop_in')->name('students_drop_in');
        Route::any('drop_all','StudentController@drop_all')->name('students_drop_all');
        Route::any('drop_mail_config','StudentController@drop_mail_config')->name('students_drop_mail_config');
    });

    Route::prefix('Class')->group(function (){
        Route::resource('course','CourseController');
        Route::resource('course_level','CourseLevelController',['only'=>['index','create','destroy']]);
        Route::resource('course_data','CourseDataController');
        Route::resource('subject_class','SubjectClassController');
        Route::resource('sup_elective','SupElectiveController');
    });

    Route::prefix('Grade')->group(function (){
        Route::resource('work_grade','WorkGradeController');
        Route::resource('UnReport','UnreportController',['only'=>['index']]);
        Route::post('UnReport_mail','UnreportController@mail_notice')->name('UnReport_mail');
        Route::post('UnReport_all_mail','UnreportController@all_mail_notice')->name('UnReport_all_mail');
        Route::resource('students_grade','StudentGradeController');
        Route::get('de_sing','GradeController@de_sing')->name('de_sing');
        Route::get('de_sing_list_grade','GradeController@de_sing_list_grade')->name('de_sing_list_grade');
    });

    Route::prefix('Update')->group(function (){
        Route::resource('students_update','StudentsUpdateController');
        Route::post('all_update','StudentsUpdateController@all_update')->name('update');
        Route::post('exception_update/{id}','StudentsUpdateController@exception_update')->name('exception_update');
        Route::post('keyin_exception_update','StudentsUpdateController@keyin_exception_update')->name('keyin_exception_update');
        Route::resource('recode_update','UpdateRecodeController');
    });

//    Route::prefix('Forum')->group(function (){
//        Route::prefix('theme')->group(function (){
//            Route::any('theme','ForumController@theme')->name('forum_theme');
//            Route::post('/add','ForumController@theme_add')->name('forum_theme_add');
//            Route::post('/edit/{id}','ForumController@theme_edit')->name('forum_theme_edit');
//            Route::post('/delete/{id}','ForumController@theme_delete')->name('forum_theme_delete');
//        });
//    });

    Route::prefix('announcement')->group(function (){
        Route::resource('bulletin','BulletinController');
        Route::post('create_type','BulletinController@create_type')->name('create_type');
        Route::delete('delete_relies/{replies}','BulletinController@delete_relies')->name('delete_relies');
    });

    Route::prefix('email_config')->group(function (){
        Route::prefix('drop')->group(function (){
            Route::any('/','EmailController@drop_show')->name('email_config_drop');
            Route::post('out/{type}','EmailController@email_config')->name('email_config_dropout');
            Route::post('in/{type}','EmailController@email_config')->name('email_config_dropin');
        });
        Route::prefix('update')->group(function (){
            Route::any('/','EmailController@update_show')->name('email_config_update');
            Route::post('save/{type}','EmailController@email_config')->name('email_config_update_save');
        });
        Route::prefix('enrollment')->group(function (){
           Route::any('/','EmailController@enrollment_show')->name('email_config_enrollment');
           Route::post('save/{type}','EmailController@email_config')->name('email_config_enrollment_save');
        });
    });

    Route::prefix('Edit')->group(function (){
        //入學指導
        Route::prefix('guidance')->group(function (){
            Route::any('/','EditController@admission_guidance')->name('edit_admission_guidance');
            Route::post('save/{type}','EditController@edit')->name('edit_admission_guidance_save');
        });
        //教學計畫
        Route::prefix('plan')->group(function (){
            Route::any('/','EditController@plan')->name('edit_plan');
            Route::post('save/{type}','EditController@edit')->name('edit_plan_save');
        });
        //認識學院
        Route::prefix('understanding')->group(function (){
            Route::any('/','EditController@understanding')->name('edit_understanding');
            Route::post('save/{type}','EditController@edit')->name('edit_understanding_save');
        });
        //年度行事曆
        Route::prefix('calendar')->group(function (){
            Route::any('/','EditCalendarController@calendar')->name('edit_calendar');
            Route::post('/save/{year}/{month}','EditCalendarController@calendar_save')->name('calendar_save');
        });
        //說明看板
        Route::prefix('description')->group(function (){
            Route::any('/','EditController@description')->name('edit_description');
            Route::post('save/{type}','EditController@edit')->name('edit_description_save');
        });
        //訊息公告
        Route::prefix('announcement')->group(function (){
            Route::any('/','EditController@announcement')->name('edit_announcement');
            Route::post('/mange/{config}','EditController@announcement_mange')->name('edit_announcement_mange');
            Route::post('/save/{type}','EditController@edit')->name('edit_announcement_save');
        });
    });

    Route::prefix('File')->group(function (){
        Route::resource('scripture','FileScriptureController');
        Route::resource('teaching_material','FileTeachingMaterial');
    });

    Route::prefix('administration')->group(function (){
        Route::resource('role','RoleController');
        Route::resource('account','AccountController');
    });
});

Route::any('test','TestController@test');
//Route::any('testshow','TestController@testshow');

app/Http/Controllers/SubjectClassController.php
<?php

namespace App\Http\Controllers;

use App\course_data;
use App\Course_level;
use App\Curriculum;
use App\Rules\Check_Course;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class SubjectClassController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        try{
            $id = $request->query('class',1);
            $level = Course_level::all();
            $data = Course_level::find($id);
            $course = course_data::all();
        }catch (\Exception $e){
            Log::info($e->getMessage());
            abort(403,'頁面錯誤.');
        }
        return view('admin.Subject_class.subject_class',compact('level','data','course','id'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            $validatedData = $request->validate([
                'level' => 'required',
                'course_data' => ['required',new Check_Course($request->level)],
                'report' => 'required',
                'compulsory' => 'required',
                'remark' => 'nullable'
            ]);

            DB::transaction(function ()use($validatedData){
                Curriculum::create($validatedData);
            });

            DB::commit();
        }catch (\Exception $e){
            DB::rollBack();
            Log::info($e->getMessage());
        }
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Curriculum $subject_class
     * @return void
     */
    public function edit(Curriculum $subject_class)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Curriculum $subject_class
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Curriculum $subject_class)
    {
        try{
            $validatedData = $request->validate([
                'level' => 'required',
                'course_data' => 'required',
                'report' => 'required',
                'compulsory' => 'required',
                'remark' => 'nullable'
            ]);

            DB::transaction(function ()use($validatedData,$subject_class){
                $subject_class->update($validatedData);
            });

            DB::commit();
        }catch (\Exception $e){
            DB::rollBack();
            Log::info($e->getMessage());
        }
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Curriculum $subject_class
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Curriculum $subject_class)
    {
        try{
            DB::transaction(function ()use($subject_class){
                $subject_class->delete();
            });
            DB::commit();
        }catch (\Exception $e){
            DB::rollBack();
            Log::info($e->getMessage());
        }
        return back();
    }
}

resources/views/admin/Subject_class/subject_class.blade.php
@extends('admin.layouts.layout')
@push('script')
<script>
    $(document).ready(function () {
        $('li[name=course_li]').addClass('active');
        $('div[name=course]').addClass('show');

        // $('.nav-item a').click(function () {
        //     var arr = $(this).attr('href').split('-');
        //     $('#create_form').attr('action','/admin/Class/subject_class/create/'+arr[1]);
        // });
    });
</script>
@endpush
@section('navbar')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">科目學分課程</li>
        <li class="breadcrumb-item active"><b>科目學分編輯</b></li>
    </ol>
@endsection
@section('content')
    <div class="content-wrapper">
        <div class="container-fluid">

            <div class="row">
                <div class="col-12">
                    <ul class="nav nav-tabs nav-justified" role="tablist">
                        @foreach($level as $v)
                        <li class="nav-item">
                            <a class="nav-link {{ $v->id == $id ?"active":"" }}"  href="{{ route('subject_class.index',['class'=>$v->id]) }}">{{ $v->level }}</a>
                        </li>
                        @endforeach
                    </ul>
                </div>
                <div class="col-12 pt-4" >
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <h3>
                        <div class="row">
                            <div class="col-6">{{ $data->level }}</div>
                            <div class="col-6 text-right">
                                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add">
                                    <i class="fa fa-calendar-plus-o"></i> 新增課程
                                </button>
                            </div>
                        </div>
                    </h3>
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>管理</th>
                            <th>課程編號</th>
                            <th>課程名稱</th>
                            <th>修別</th>
                            <th>授課老師</th>
                            <th>提交報告</th>
                            <th style="width: 30%">備註</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($data->curricula->where('level',$id) as $l)
                            <tr>
                                <td>
                                    <a href="#delete{{ $l->id }}" data-toggle="modal" style="color: red;font-size: 1.3rem"><i class="fa fa-trash"></i></a>&nbsp;&nbsp;&nbsp;
                                    <a href="#modify{{ $l->id }}" data-toggle="modal" style="color: blue;font-size: 1.3rem"><i class="fa fa-edit"></i></a>&nbsp;&nbsp;&nbsp;
                                </td>
                                <td>{{ $l->coursedata->sn }}</td>
                                <td>{{ $l->coursedata->title }}</td>
                                <td>{{ $l->compulsory == 1?"必修":"選修" }}</td>
                                <td>{{ $l->coursedata->teacher }}</td>
                                <td style="text-align: center">{!! $l->report == 0 ?"<i class='fas fa-times' style='font-size: 1.3rem;color: red'>": "<i class='fa fa-check' style='font-size: 1.3rem;color: green'></i>" !!}</td>
                                <td>{{ $l->remark }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- /.container-fluid-->
    </div>
@endsection
@include('admin.Subject_class.modals.subject_class_add')
@include('admin.Subject_class.modals.subject_class_modify')
@include('admin.Subject_class.modals.subject_class_delete')