routes/web.php
<?php

Route::prefix('admin')->group(function (){

    Route::get('/','LoginController@login')->name('login');
//    ->middleware('LoginValidate')
    Route::post('validatedData','LoginController@validatedData')->name('validatedData');
    Route::post('logout/{user}','LoginController@logout')->name('logout');

    Route::resource('dashboard','DashboardController');
//    ->middleware('ValidateUser')
    Route::prefix('students')->group(function (){
        Route::resource('data', 'StuDataController',['except'=>['create','store']]);
        Route::resource('black_list','BlackListController');
        Route::any('drop_out','StudentController@drop_out')->name('students_drop_out');
        Route::any('drop_in','StudentController@drop_in')->name('students_drop_in');
        Route::any('drop_all','StudentController@drop_all')->name('students_drop_all');
        Route::any('drop_mail_config','StudentController@drop_mail_config')->name('students_drop_mail_config');
    });

    Route::prefix('Class')->group(function (){
        Route::resource('course','CourseController');
        Route::resource('course_level','CourseLevelController',['only'=>['index','create','destroy']]);
        Route::resource('course_data','CourseDataController');
        Route::resource('subject_class','SubjectClassController');
        Route::resource('sup_elective','SupElectiveController');
    });

    Route::prefix('Grade')->group(function (){
        Route::resource('work_grade','WorkGradeController');
        Route::resource('UnReport','UnreportController',['only'=>['index']]);
        Route::post('UnReport_mail','UnreportController@mail_notice')->name('UnReport_mail');
        Route::post('UnReport_all_mail','UnreportController@all_mail_notice')->name('UnReport_all_mail');
        Route::resource('students_grade','StudentGradeController');
        Route::get('de_sing','GradeController@de_sing')->name('de_sing');
        Route::get('de_sing_list_grade','GradeController@de_sing_list_grade')->name('de_sing_list_grade');
    });

    Route::prefix('Update')->group(function (){
        Route::resource('students_update','StudentsUpdateController');
        Route::post('all_update','StudentsUpdateController@all_update')->name('update');
        Route::post('exception_update/{id}','StudentsUpdateController@exception_update')->name('exception_update');
        Route::post('keyin_exception_update','StudentsUpdateController@keyin_exception_update')->name('keyin_exception_update');
        Route::resource('recode_update','UpdateRecodeController');
    });

//    Route::prefix('Forum')->group(function (){
//        Route::prefix('theme')->group(function (){
//            Route::any('theme','ForumController@theme')->name('forum_theme');
//            Route::post('/add','ForumController@theme_add')->name('forum_theme_add');
//            Route::post('/edit/{id}','ForumController@theme_edit')->name('forum_theme_edit');
//            Route::post('/delete/{id}','ForumController@theme_delete')->name('forum_theme_delete');
//        });
//    });

    Route::prefix('announcement')->group(function (){
        Route::resource('bulletin','BulletinController');
        Route::post('create_type','BulletinController@create_type')->name('create_type');
        Route::delete('delete_relies/{replies}','BulletinController@delete_relies')->name('delete_relies');
    });

    Route::prefix('email_config')->group(function (){
        Route::prefix('drop')->group(function (){
            Route::any('/','EmailController@drop_show')->name('email_config_drop');
            Route::post('out/{type}','EmailController@email_config')->name('email_config_dropout');
            Route::post('in/{type}','EmailController@email_config')->name('email_config_dropin');
        });
        Route::prefix('update')->group(function (){
            Route::any('/','EmailController@update_show')->name('email_config_update');
            Route::post('save/{type}','EmailController@email_config')->name('email_config_update_save');
        });
        Route::prefix('enrollment')->group(function (){
           Route::any('/','EmailController@enrollment_show')->name('email_config_enrollment');
           Route::post('save/{type}','EmailController@email_config')->name('email_config_enrollment_save');
        });
    });

    Route::prefix('Edit')->group(function (){
        //入學指導
        Route::prefix('guidance')->group(function (){
            Route::any('/','EditController@admission_guidance')->name('edit_admission_guidance');
            Route::post('save/{type}','EditController@edit')->name('edit_admission_guidance_save');
        });
        //教學計畫
        Route::prefix('plan')->group(function (){
            Route::any('/','EditController@plan')->name('edit_plan');
            Route::post('save/{type}','EditController@edit')->name('edit_plan_save');
        });
        //認識學院
        Route::prefix('understanding')->group(function (){
            Route::any('/','EditController@understanding')->name('edit_understanding');
            Route::post('save/{type}','EditController@edit')->name('edit_understanding_save');
        });
        //年度行事曆
        Route::prefix('calendar')->group(function (){
            Route::any('/','EditCalendarController@calendar')->name('edit_calendar');
            Route::post('/save/{year}/{month}','EditCalendarController@calendar_save')->name('calendar_save');
        });
        //說明看板
        Route::prefix('description')->group(function (){
            Route::any('/','EditController@description')->name('edit_description');
            Route::post('save/{type}','EditController@edit')->name('edit_description_save');
        });
        //訊息公告
        Route::prefix('announcement')->group(function (){
            Route::any('/','EditController@announcement')->name('edit_announcement');
            Route::post('/mange/{config}','EditController@announcement_mange')->name('edit_announcement_mange');
            Route::post('/save/{type}','EditController@edit')->name('edit_announcement_save');
        });
    });

    Route::prefix('File')->group(function (){
        Route::resource('scripture','FileScriptureController');
        Route::resource('teaching_material','FileTeachingMaterial');
    });

    Route::prefix('administration')->group(function (){
        Route::resource('role','RoleController');
        Route::resource('account','AccountController');
    });
});

Route::any('test','TestController@test');
//Route::any('testshow','TestController@testshow');

app/Http/Controllers/SubjectClassController.php
<?php

namespace App\Http\Controllers;

use App\course_data;
use App\Course_level;
use App\Curriculum;
use App\Rules\Check_Course;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class SubjectClassController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        try{
            $id = $request->query('class',1);
            $level = Course_level::all();
            $data = Course_level::find($id);
            $course = course_data::all();
        }catch (\Exception $e){
            Log::info($e->getMessage());
            abort(403,'頁面錯誤.');
        }
        return view('admin.Subject_class.subject_class',compact('level','data','course','id'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            $validatedData = $request->validate([
                'level' => 'required',
                'course_data' => ['required',new Check_Course($request->level)],
                'report' => 'required',
                'compulsory' => 'required',
                'remark' => 'nullable'
            ]);

            DB::transaction(function ()use($validatedData){
                Curriculum::create($validatedData);
            });

            DB::commit();
        }catch (\Exception $e){
            DB::rollBack();
            Log::info($e->getMessage());
        }
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Curriculum $subject_class
     * @return void
     */
    public function edit(Curriculum $subject_class)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Curriculum $subject_class
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Curriculum $subject_class)
    {
        try{
            $validatedData = $request->validate([
                'level' => 'required',
                'course_data' => 'required',
                'report' => 'required',
                'compulsory' => 'required',
                'remark' => 'nullable'
            ]);

            DB::transaction(function ()use($validatedData,$subject_class){
                $subject_class->update($validatedData);
            });

            DB::commit();
        }catch (\Exception $e){
            DB::rollBack();
            Log::info($e->getMessage());
        }
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Curriculum $subject_class
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Curriculum $subject_class)
    {
        try{
            DB::transaction(function ()use($subject_class){
                $subject_class->delete();
            });
            DB::commit();
        }catch (\Exception $e){
            DB::rollBack();
            Log::info($e->getMessage());
        }
        return back();
    }
}

resources/views/admin/Subject_class/modals/subject_class_add.blade.php
<!-- The Modal -->
<div class="modal" id="add">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="{{ route('subject_class.store') }}" id="create_form" method="POST">
                @csrf
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">新增課程</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    <input type="hidden" name="level" value="{{ $data->id }}">
                    <div class="form-group">
                        <label for="class">課程：</label>
                        <select class="form-control" id="course_data" name="course_data">
                            @foreach($course as $c)
                            <option value="{{ $c->id }}">{{ $c->sn."-".$c->title }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="class_type">修別：</label>
                        <div class="form-check-inline">
                            <label class="form-check-label">
                                <input type="radio" class="form-check-input" name="compulsory" value="1">必修
                            </label>
                        </div>
                        <div class="form-check-inline">
                            <label class="form-check-label">
                                <input type="radio" class="form-check-input" name="compulsory" value="2">選修
                            </label>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="class_homework">提交報告：</label>
                        <div class="form-check-inline">
                            <label class="form-check-label">
                                <input type="radio" class="form-check-input" name="report" value="1"><i class="fa fa-check" style="font-size: 1.3rem;color: green"></i>
                            </label>
                        </div>
                        <div class="form-check-inline">
                            <label class="form-check-label">
                                <input type="radio" class="form-check-input" name="report" value="0"><i class="fas fa-times" style="font-size: 1.3rem;color: red"></i>
                            </label>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="pwd">備註：</label>
                        <textarea class="form-control" rows="3" id="remark" name="remark"></textarea>
                    </div>

                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">新增</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">取消</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/admin/Subject_class/modals/subject_class_delete.blade.php
@foreach($data->curricula->where('level',$id) as $l)
    <!-- The Modal -->
    <div class="modal" id="delete{{ $l->id }}">
        <div class="modal-dialog">
            <form class="modal-content" action="{{ route('subject_class.destroy',['subject_class'=>$l]) }}" method="POST">
                @method('DELETE')
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">刪除</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body" style="color: red;font-size: 1.3rem">
                    確定刪除“{{ $l->coursedata->sn }}__{{ $l->coursedata->title }}“課程？
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">刪除</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">取消</button>
                </div>
            </form>
        </div>
    </div>
@endforeach

resources/views/admin/Subject_class/modals/subject_class_modify.blade.php
<!-- The Modal -->
@foreach($data->curricula->where('level',$id) as $l)
<div class="modal" id="modify{{ $l->id }}">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="{{ route('subject_class.update',['subject_class'=>$l]) }}" id="create_form" method="POST">
                @method('PATCH')
                @csrf
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">修改課程</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    <input type="hidden" name="level" value="{{ $data->id }}">

                    <div class="form-group">
                        <label for="class">課程：</label>
                        <select class="form-control" id="course_data" name="course_data">
                            @foreach($course as $c)
                                <option value="{{ $c->id }}" {{ $l->course_data == $c->id ? "selected":""}}>{{ $c->sn."-".$c->title }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="class_type">修別：</label>
                        <div class="form-check-inline">
                            <label class="form-check-label">
                                <input type="radio" class="form-check-input" name="compulsory" value="1" {{ $l->compulsory == 1 ? "checked":"" }}>必修
                            </label>
                        </div>
                        <div class="form-check-inline">
                            <label class="form-check-label">
                                <input type="radio" class="form-check-input" name="compulsory" value="2" {{ $l->compulsory == 2 ? "checked":"" }}>選修
                            </label>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="class_homework">提交報告：</label>
                        <div class="form-check-inline">
                            <label class="form-check-label">
                                <input type="radio" class="form-check-input" name="report" value="1" {{ $l->report == 1 ? "checked":"" }}><i class="fa fa-check" style="font-size: 1.3rem;color: green"></i>
                            </label>
                        </div>
                        <div class="form-check-inline">
                            <label class="form-check-label">
                                <input type="radio" class="form-check-input" name="report" value="0" {{ $l->report == 0 ? "checked":"" }}><i class="fas fa-times" style="font-size: 1.3rem;color: red"></i>
                            </label>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="pwd">備註：</label>
                        <textarea class="form-control" rows="3" id="remark" name="remark">{{ $l->remark }}</textarea>
                    </div>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">修改</button>

                    <button type="button" class="btn btn-danger" data-dismiss="modal">取消</button>
                </div>
            </form>

        </div>
    </div>
</div>
@endforeach