routes/web.php
<?php

Route::prefix('admin')->group(function (){

    Route::get('/','LoginController@login')->name('login');
//    ->middleware('LoginValidate')
    Route::post('validatedData','LoginController@validatedData')->name('validatedData');
    Route::post('logout/{user}','LoginController@logout')->name('logout');

    Route::resource('dashboard','DashboardController');
//    ->middleware('ValidateUser')
    Route::prefix('students')->group(function (){
        Route::resource('data', 'StuDataController',['except'=>['create','store']]);
        Route::resource('black_list','BlackListController');
        Route::any('drop_out','StudentController@drop_out')->name('students_drop_out');
        Route::any('drop_in','StudentController@drop_in')->name('students_drop_in');
        Route::any('drop_all','StudentController@drop_all')->name('students_drop_all');
        Route::any('drop_mail_config','StudentController@drop_mail_config')->name('students_drop_mail_config');
    });

    Route::prefix('Class')->group(function (){
        Route::resource('course','CourseController');
        Route::resource('course_level','CourseLevelController',['only'=>['index','create','destroy']]);
        Route::resource('course_data','CourseDataController');
        Route::resource('subject_class','SubjectClassController');
        Route::resource('sup_elective','SupElectiveController');
    });

    Route::prefix('Grade')->group(function (){
        Route::resource('work_grade','WorkGradeController');
        Route::resource('UnReport','UnreportController',['only'=>['index']]);
        Route::post('UnReport_mail','UnreportController@mail_notice')->name('UnReport_mail');
        Route::post('UnReport_all_mail','UnreportController@all_mail_notice')->name('UnReport_all_mail');
        Route::resource('students_grade','StudentGradeController');
        Route::get('de_sing','GradeController@de_sing')->name('de_sing');
        Route::get('de_sing_list_grade','GradeController@de_sing_list_grade')->name('de_sing_list_grade');
    });

    Route::prefix('Update')->group(function (){
        Route::resource('students_update','StudentsUpdateController');
        Route::post('all_update','StudentsUpdateController@all_update')->name('update');
        Route::post('exception_update/{id}','StudentsUpdateController@exception_update')->name('exception_update');
        Route::post('keyin_exception_update','StudentsUpdateController@keyin_exception_update')->name('keyin_exception_update');
        Route::resource('recode_update','UpdateRecodeController');
    });

//    Route::prefix('Forum')->group(function (){
//        Route::prefix('theme')->group(function (){
//            Route::any('theme','ForumController@theme')->name('forum_theme');
//            Route::post('/add','ForumController@theme_add')->name('forum_theme_add');
//            Route::post('/edit/{id}','ForumController@theme_edit')->name('forum_theme_edit');
//            Route::post('/delete/{id}','ForumController@theme_delete')->name('forum_theme_delete');
//        });
//    });

    Route::prefix('announcement')->group(function (){
        Route::resource('bulletin','BulletinController');
        Route::post('create_type','BulletinController@create_type')->name('create_type');
        Route::delete('delete_relies/{replies}','BulletinController@delete_relies')->name('delete_relies');
    });

    Route::prefix('email_config')->group(function (){
        Route::prefix('drop')->group(function (){
            Route::any('/','EmailController@drop_show')->name('email_config_drop');
            Route::post('out/{type}','EmailController@email_config')->name('email_config_dropout');
            Route::post('in/{type}','EmailController@email_config')->name('email_config_dropin');
        });
        Route::prefix('update')->group(function (){
            Route::any('/','EmailController@update_show')->name('email_config_update');
            Route::post('save/{type}','EmailController@email_config')->name('email_config_update_save');
        });
        Route::prefix('enrollment')->group(function (){
           Route::any('/','EmailController@enrollment_show')->name('email_config_enrollment');
           Route::post('save/{type}','EmailController@email_config')->name('email_config_enrollment_save');
        });
    });

    Route::prefix('Edit')->group(function (){
        //入學指導
        Route::prefix('guidance')->group(function (){
            Route::any('/','EditController@admission_guidance')->name('edit_admission_guidance');
            Route::post('save/{type}','EditController@edit')->name('edit_admission_guidance_save');
        });
        //教學計畫
        Route::prefix('plan')->group(function (){
            Route::any('/','EditController@plan')->name('edit_plan');
            Route::post('save/{type}','EditController@edit')->name('edit_plan_save');
        });
        //認識學院
        Route::prefix('understanding')->group(function (){
            Route::any('/','EditController@understanding')->name('edit_understanding');
            Route::post('save/{type}','EditController@edit')->name('edit_understanding_save');
        });
        //年度行事曆
        Route::prefix('calendar')->group(function (){
            Route::any('/','EditCalendarController@calendar')->name('edit_calendar');
            Route::post('/save/{year}/{month}','EditCalendarController@calendar_save')->name('calendar_save');
        });
        //說明看板
        Route::prefix('description')->group(function (){
            Route::any('/','EditController@description')->name('edit_description');
            Route::post('save/{type}','EditController@edit')->name('edit_description_save');
        });
        //訊息公告
        Route::prefix('announcement')->group(function (){
            Route::any('/','EditController@announcement')->name('edit_announcement');
            Route::post('/mange/{config}','EditController@announcement_mange')->name('edit_announcement_mange');
            Route::post('/save/{type}','EditController@edit')->name('edit_announcement_save');
        });
    });

    Route::prefix('File')->group(function (){
        Route::resource('scripture','FileScriptureController');
        Route::resource('teaching_material','FileTeachingMaterial');
    });

    Route::prefix('administration')->group(function (){
        Route::resource('role','RoleController');
        Route::resource('account','AccountController');
    });
});

Route::any('test','TestController@test');
//Route::any('testshow','TestController@testshow');

app/Bulletin.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bulletin extends Model
{
    protected $guarded = [];

    public function get_replies(){
        return $this->hasMany('App\Bulletin_replies','bulletin');
    }

    public function get_type(){
        return $this->belongsTo('App\Bulletin_type','type');
    }
}

app/Bulletin_type.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bulletin_type extends Model
{
    protected $guarded = [];

    public function get_bulletin(){
        return $this->hasMany('App\Bulletin','type');
    }
}

app/Http/Controllers/BulletinController.php
<?php

namespace App\Http\Controllers;

use App\Bulletin;
use App\Bulletin_replies;
use App\Bulletin_type;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class BulletinController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        try{
            $select = $request->query('id',1);
            $type = Bulletin_type::all();
            $news = Bulletin::where('type',$select)->get();
        } catch (\Exception $e) {
            Log::info($e->getMessage());
            abort(403, '頁面資訊錯誤');
        }
        return view('admin.Bulletin.announcement', compact('type','select','news'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            DB::transaction(function ()use($request){
                $validatedData = $request->validate([
                    'type' => 'required',
                    'title' => 'required',
                    'content' => 'required',
                ]);
                Bulletin::create($validatedData);
            });
            DB::commit();
        }catch (\Exception $e){
            Log::info($e->getMessage());
            DB::rollBack();
        }
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param Bulletin $bulletin
     * @return \Illuminate\Http\Response
     */
    public function show(Bulletin $bulletin)
    {
        return view('admin.Bulletin.replies',compact('bulletin'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Bulletin $bulletin
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Bulletin $bulletin)
    {
        try{
            DB::transaction(function ()use($request,$bulletin){
                $validatedData = $request->validate([
                    'type' => 'required',
                    'title' => 'required',
                    'content' => 'required',
                ]);
                $bulletin->update($validatedData);
            });
            DB::commit();
        }catch (\Exception $e){
            Log::info($e->getMessage());
            DB::rollBack();
        }

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Bulletin $bulletin
     * @return \Illuminate\Http\Response
     */
    public function destroy(Bulletin $bulletin)
    {
        try{
            DB::transaction(function ()use($bulletin){
               $bulletin->delete();
            });
            DB::commit();
        }catch (\Exception $e){
            DB::rollBack();
            Log::info($e->getMessage());
        }
        return back();
    }

    public function create_type(Request $request){
        $validatedData = $request->validate([
            'name' => 'required',
        ]);
        Bulletin_type::create($validatedData);

        return back();
    }

    public function delete_relies(Bulletin_replies $replies){
        $replies->delete();
        return back();
    }
}

resources/views/admin/Bulletin/modals/add.blade.php
@if(!empty($type))
    <!-- The Modal -->
    <div class="modal" id="add">
        <div class="modal-dialog modal-xl">
            <form class="modal-content" action="{{ route('bulletin.store') }}" method="post">
                @csrf
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">新增公告消息</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <form>
                    <!-- Modal body -->
                    <div class="modal-body" style="font-size: 1.3rem">
                        <div class="form-group">
                            <label for="type">公告類型：</label>
                            <select class="form-control" id="type" name="type">
                                @foreach($type as $t)
                                    <option value="{{ $t->id }}">{{ $t->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="title">標題:</label>
                            <input type="text" class="form-control" id="title" name="title">
                        </div>
                        <div class="form-group">
                            <label for="announcement_content">內容:</label>
                            <textarea class="announcement_content" id="announcement_content" name="content"></textarea>
                        </div>
                    </div>
                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">送出</button>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">取消</button>
                    </div>
                </form>
            </form>
        </div>
    </div>
@endif

resources/views/admin/Bulletin/modals/delete.blade.php
@foreach($news as $v)
<!-- The Modal -->
<div class="modal" id="delete{{ $v->id }}">
    <div class="modal-dialog">
        <form class="modal-content" action="{{ route('bulletin.destroy',['bulletin'=>$v]) }}" method="POST">
            @method('DELETE')
            @csrf
            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">刪除</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <h2>{{ $v->title }}</h2>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">刪除</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">取消</button>
            </div>
        </form>
    </div>
</div>
@endforeach

resources/views/admin/Bulletin/modals/delete_relies.blade.php
@foreach($bulletin->get_replies as $replies)
    <!-- The Modal -->
    <div class="modal" id="delete{{ $v->id }}">
        <div class="modal-dialog">
            <form class="modal-content" action="{{ route('delete_relies',['replies'=>$replies]) }}" method="POST">
            @method('DELETE')
            @csrf
            <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">刪除</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    <h2>確定刪除此留言？</h2>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">刪除</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">取消</button>
                </div>
            </form>
        </div>
    </div>
@endforeach

resources/views/admin/Bulletin/modals/edit.blade.php
@foreach($news as $v)
    <!-- The Modal -->
    <div class="modal" id="edit{{ $v->id }}">
        <div class="modal-dialog modal-xl">
            <form class="modal-content" action="{{ route('bulletin.update',['bulletin'=>$v]) }}" method="post">
                @method('PATCH')
                @csrf
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">修改公告消息</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <form>
                    <!-- Modal body -->
                    <div class="modal-body" style="font-size: 1.3rem">
                        <div class="form-group">
                            <label for="type">公告類型：</label>
                            <select class="form-control" id="type" name="type">
                                @foreach($type as $t)
                                    <option value="{{ $t->id }}" {{ $t->id == $select ? "selected":"" }}>{{ $t->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="title">標題:</label>
                            <input type="text" class="form-control" id="title" name="title" value="{{ $v->title }}">
                        </div>
                        <div class="form-group">
                            <label for="announcement_content">內容:</label>
                            <textarea class="announcement_content" id="announcement_content" name="announcement_content">{{ $v->content }}</textarea>
                        </div>
                    </div>
                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">送出</button>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">取消</button>
                    </div>
                </form>
            </form>
        </div>
    </div>
@endforeach

resources/views/admin/Bulletin/modals/type_add.blade.php
<!-- The Modal -->
<div class="modal" id="type_add">
    <div class="modal-dialog">
        <form class="modal-content" action="{{ route('create_type') }}" method="POST">
            @csrf
            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">新增公告類型</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
                <!-- Modal body -->
                <div class="modal-body">
                    <div class="form-group">
                        <label for="type">類型:</label>
                        <input type="text" class="form-control" id="type" name="name">
                    </div>
                </div>
                <!-- Modal footer -->
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">送出</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">取消</button>
                </div>
        </form>
    </div>
</div>